name: main ブランチにマージを許可したブランチかチェックする
# Check if branch can be merged to main
# `feature/xxx` または `hotfix/xxx` から `main` へのマージは許可する

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch name does not start with feature/ or hotfix/
        if: ${{ !startsWith(github.head_ref, 'feature') && !startsWith(github.head_ref, 'hotfix')  }}
        run: |
          echo "Error: Branch names should start with 'feature/' or 'hotfix/'."
          exit 1
